# Selecting columns

In [1]:
import pandas as pd

cities = pd.read_csv("../data/cities.csv")

Select one column by placing its name in square brackets.

In [2]:
cities["Name"]

0        Abbotsford
1           Airdrie
2              Ajax
3              Alma
4            Aurora
           ...
174         Windsor
175        Winnipeg
176    Wood Buffalo
177       Woodstock
178        Woolwich
Name: Name, Length: 179, dtype: object

Select several columns by supplying a list of column names. The double brackets appear because the inner brackets create the list.

In [3]:
cities[["Name", "Population, 2021"]]

             Name  Population, 2021
0      Abbotsford          153524.0
1         Airdrie           74100.0
2            Ajax          126666.0
3            Alma           30331.0
4          Aurora           62057.0
..            ...               ...
174       Windsor          229660.0
175      Winnipeg          749607.0
176  Wood Buffalo           72326.0
177     Woodstock           46705.0
178      Woolwich           26999.0

[179 rows x 2 columns]

The original DataFrame is unchanged. Store the result in a new variable when you want to reuse it.

In [4]:
city_populations = cities[["Name", "Population, 2021"]]
city_populations.head()

         Name  Population, 2021
0  Abbotsford          153524.0
1     Airdrie           74100.0
2        Ajax          126666.0
3        Alma           30331.0
4      Aurora           62057.0