# Sorting rows

In [1]:
import pandas as pd

cities = pd.read_csv("../data/cities.csv")

Sort from largest to smallest by setting `ascending=False`.

In [2]:
largest_first = cities.sort_values(
    by="Population, 2021",
    ascending=False
)

largest_first.head(10)

            Name Prov/terr  Population, 2021  Population, 2016
158      Toronto      Ont.         2794356.0         2731571.0
89      Montréal      Que.         1762949.0         1704694.0
19       Calgary     Alta.         1306784.0         1239220.0
106       Ottawa      Ont.         1017449.0          934243.0
42      Edmonton     Alta.         1010899.0          933088.0
175     Winnipeg      Man.          749607.0          705244.0
87   Mississauga      Ont.          717961.0          721599.0
161    Vancouver      B.C.          662248.0          631486.0
11      Brampton      Ont.          656480.0          593638.0
56      Hamilton      Ont.          569353.0          536917.0

Filtering and sorting can be completed in separate, easy-to-inspect steps.

In [3]:
ontario_cities = cities.loc[
    cities["Prov/terr"] == "Ont."
]

ontario_cities = ontario_cities.sort_values(
    by="Population, 2021",
    ascending=False
)

ontario_cities.head(10)

            Name Prov/terr  Population, 2021  Population, 2016
158      Toronto      Ont.         2794356.0         2731571.0
106       Ottawa      Ont.         1017449.0          934243.0
87   Mississauga      Ont.          717961.0          721599.0
11      Brampton      Ont.          656480.0          593638.0
56      Hamilton      Ont.          569353.0          536917.0
76        London      Ont.          422324.0          383822.0
81       Markham      Ont.          338503.0          328966.0
163      Vaughan      Ont.          323103.0          306233.0
63     Kitchener      Ont.          256885.0          233222.0
174      Windsor      Ont.          229660.0          217188.0